# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

send_SIGINT <- function(pid) {
    .Call(`_rdaemon_send_SIGINT`, pid)
}

detachConsole <- function() {
    invisible(.Call(`_rdaemon_detachConsole`))
}

getNameMaxLen <- function() {
    .Call(`_rdaemon_getNameMaxLen`)
}

existsGlobalVariable <- function(sharedMemoryName) {
    .Call(`_rdaemon_existsGlobalVariable`, sharedMemoryName)
}

setGlobalVariable <- function(sharedMemoryName, value) {
    invisible(.Call(`_rdaemon_setGlobalVariable`, sharedMemoryName, value))
}

getGlobalVariable <- function(sharedMemoryName) {
    .Call(`_rdaemon_getGlobalVariable`, sharedMemoryName)
}

unsetGlobalVariable <- function(sharedMemoryName) {
    invisible(.Call(`_rdaemon_unsetGlobalVariable`, sharedMemoryName))
}

isProcessRunning <- function(pid) {
    .Call(`_rdaemon_isProcessRunning`, pid)
}

